services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'varejolocal'
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD: 'Vitor12345'
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql  
volumes:
  mysql-volume:
    driver: local     
      