spring:
  datasource:
    url: jdbc:mysql://localhost:3306/varejolocal
    username: developer
    password: Vitor12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true    
  h2: 
    console: 
     enabled: true
     path: /h2-console