spring:
  jackson:
    time-zone: America/Sao_Paulo
  profiles:
    active: "docker"
  datasource:
    url: jdbc:mysql://localhost:3306/varejolocal
    username: admin
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    
  h2: 
    console: 
     enabled: true
     path: /h2-console
  sql:
    init:
      schema-locations: classpath:data.sql
jwt:
 public:
  key: classpath:${PUB_KEY}
 private:
  key: classpath:${PRIVATE_KEY}
OrderItemController:
  url: "http://localhost:8080/orderItems"
         